//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tosan.TeamFoundation.Plugins.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FieldNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tosan.TeamFoundation.Plugins.Resources.FieldNames", typeof(FieldNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.VSTS.Common.Activity.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.ActivityId.
        /// </summary>
        internal static string ActivityId {
            get {
                return ResourceManager.GetString("ActivityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.ActivityNumber.
        /// </summary>
        internal static string ActivityNumber {
            get {
                return ResourceManager.GetString("ActivityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.AreaId.
        /// </summary>
        internal static string AreaId {
            get {
                return ResourceManager.GetString("AreaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.AssignedTo.
        /// </summary>
        internal static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.BaseLineWork.
        /// </summary>
        internal static string BaseLineWork {
            get {
                return ResourceManager.GetString("BaseLineWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.BaselineWorkforNewTest.
        /// </summary>
        internal static string BaselineWorkforNewTestTask {
            get {
                return ResourceManager.GetString("BaselineWorkforNewTestTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ChangedDate.
        /// </summary>
        internal static string ChangedDate {
            get {
                return ResourceManager.GetString("ChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.ChangeList.
        /// </summary>
        internal static string ChangeList {
            get {
                return ResourceManager.GetString("ChangeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.ChangeListNecessity.
        /// </summary>
        internal static string ChangeListNecessity {
            get {
                return ResourceManager.GetString("ChangeListNecessity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.ChangeNumber.
        /// </summary>
        internal static string ChangeNumber {
            get {
                return ResourceManager.GetString("ChangeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.ChangeType.
        /// </summary>
        internal static string ChangeType {
            get {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.Client.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.Scrum.Committed.
        /// </summary>
        internal static string Commited {
            get {
                return ResourceManager.GetString("Commited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.CreatedBy.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.CreateNewTestTaskAfterRejected.
        /// </summary>
        internal static string CreateNewTestTaskAfterRejected {
            get {
                return ResourceManager.GetString("CreateNewTestTaskAfterRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string CRM_Activity_Description {
            get {
                return ResourceManager.GetString("CRM_Activity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_lookupplanreleaseversion.
        /// </summary>
        internal static string CRM_Activity_PlannedReleaseVersion {
            get {
                return ResourceManager.GetString("CRM_Activity_PlannedReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regardingobjectid.
        /// </summary>
        internal static string CRM_Activity_RFCid {
            get {
                return ResourceManager.GetString("CRM_Activity_RFCid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_scheduleddurationh.
        /// </summary>
        internal static string CRM_Activity_ScheduleddurationH {
            get {
                return ResourceManager.GetString("CRM_Activity_ScheduleddurationH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject.
        /// </summary>
        internal static string CRM_Activity_Subject {
            get {
                return ResourceManager.GetString("CRM_Activity_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_analysisactivitynumber.
        /// </summary>
        internal static string CRM_AnalysisActivity_AnalysisActivityNumber {
            get {
                return ResourceManager.GetString("CRM_AnalysisActivity_AnalysisActivityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_analysisactivity.
        /// </summary>
        internal static string CRM_AnalysisActivity_EntitySchemaName {
            get {
                return ResourceManager.GetString("CRM_AnalysisActivity_EntitySchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_scheduleddurationhours.
        /// </summary>
        internal static string CRM_AnalysisActivity_ScheduleddurationH {
            get {
                return ResourceManager.GetString("CRM_AnalysisActivity_ScheduleddurationH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_changeactivitynumber.
        /// </summary>
        internal static string CRM_ChangeActivity_ChangeActivityNumber {
            get {
                return ResourceManager.GetString("CRM_ChangeActivity_ChangeActivityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_changenumber.
        /// </summary>
        internal static string CRM_ChangeActivity_Changenumber {
            get {
                return ResourceManager.GetString("CRM_ChangeActivity_Changenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_changetype.
        /// </summary>
        internal static string CRM_ChangeActivity_ChangeType {
            get {
                return ResourceManager.GetString("CRM_ChangeActivity_ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_client.
        /// </summary>
        internal static string CRM_ChangeActivity_Client {
            get {
                return ResourceManager.GetString("CRM_ChangeActivity_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_changeactivity.
        /// </summary>
        internal static string CRM_ChangeActivity_EntitySchemaName {
            get {
                return ResourceManager.GetString("CRM_ChangeActivity_EntitySchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new_isreopened.
        /// </summary>
        internal static string CRM_ChangeActivity_IsReopened {
            get {
                return ResourceManager.GetString("CRM_ChangeActivity_IsReopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_neginlitebranchversionid.
        /// </summary>
        internal static string CRM_ChangeActivity_NeginLiteBranchVersion {
            get {
                return ResourceManager.GetString("CRM_ChangeActivity_NeginLiteBranchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_neginlitetrunkversionid.
        /// </summary>
        internal static string CRM_ChangeActivity_NeginliteTrunkVersion {
            get {
                return ResourceManager.GetString("CRM_ChangeActivity_NeginliteTrunkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_server.
        /// </summary>
        internal static string CRM_ChangeActivity_Server {
            get {
                return ResourceManager.GetString("CRM_ChangeActivity_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_webconsole.
        /// </summary>
        internal static string CRM_ChangeActivity_WebConsole {
            get {
                return ResourceManager.GetString("CRM_ChangeActivity_WebConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.CRMLink.
        /// </summary>
        internal static string CRM_Link {
            get {
                return ResourceManager.GetString("CRM_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_neginliteversion.
        /// </summary>
        internal static string CRM_NeginliteVersion_EntitySchemaName {
            get {
                return ResourceManager.GetString("CRM_NeginliteVersion_EntitySchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_name.
        /// </summary>
        internal static string CRM_NeginliteVersion_Name {
            get {
                return ResourceManager.GetString("CRM_NeginliteVersion_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_plannedreleaseversion.
        /// </summary>
        internal static string CRM_PlannedReleaseVersion_EntitySchemaName {
            get {
                return ResourceManager.GetString("CRM_PlannedReleaseVersion_EntitySchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_name.
        /// </summary>
        internal static string CRM_PlannedReleaseVersion_Name {
            get {
                return ResourceManager.GetString("CRM_PlannedReleaseVersion_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new_changelist.
        /// </summary>
        internal static string CRM_RFC_ChangeList {
            get {
                return ResourceManager.GetString("CRM_RFC_ChangeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_changerequest.
        /// </summary>
        internal static string CRM_RFC_EntitySchemaName {
            get {
                return ResourceManager.GetString("CRM_RFC_EntitySchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new_isrejectedfromtest.
        /// </summary>
        internal static string CRM_RFC_IsRejectedfromTest {
            get {
                return ResourceManager.GetString("CRM_RFC_IsRejectedfromTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new_plannedreleaseversion.
        /// </summary>
        internal static string CRM_RFC_PlannedReleaseVersion {
            get {
                return ResourceManager.GetString("CRM_RFC_PlannedReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new_tscheduledduration.
        /// </summary>
        internal static string CRM_RFC_TotalSchedulDuration {
            get {
                return ResourceManager.GetString("CRM_RFC_TotalSchedulDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new_tscheduledduration.
        /// </summary>
        internal static string CRM_RFC_TotalScheduledduration {
            get {
                return ResourceManager.GetString("CRM_RFC_TotalScheduledduration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string CRM_Team_EntitySchemaName {
            get {
                return ResourceManager.GetString("CRM_Team_EntitySchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_changelistnecessity.
        /// </summary>
        internal static string CRM_TestActivity_ChangeListNecessity {
            get {
                return ResourceManager.GetString("CRM_TestActivity_ChangeListNecessity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_developtest.
        /// </summary>
        internal static string CRM_TestActivity_DevelopTest {
            get {
                return ResourceManager.GetString("CRM_TestActivity_DevelopTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_testactivity.
        /// </summary>
        internal static string CRM_TestActivity_EntitySchemaName {
            get {
                return ResourceManager.GetString("CRM_TestActivity_EntitySchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new_isreopened.
        /// </summary>
        internal static string CRM_TestActivity_IsReopened {
            get {
                return ResourceManager.GetString("CRM_TestActivity_IsReopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_refrencepath.
        /// </summary>
        internal static string CRM_TestActivity_ReferencePath {
            get {
                return ResourceManager.GetString("CRM_TestActivity_ReferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_relatedtestcase.
        /// </summary>
        internal static string CRM_TestActivity_RelatedTestCases {
            get {
                return ResourceManager.GetString("CRM_TestActivity_RelatedTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_testactivitynumber.
        /// </summary>
        internal static string CRM_TestActivity_TestActivityNumber {
            get {
                return ResourceManager.GetString("CRM_TestActivity_TestActivityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_testenviromentconfiguration.
        /// </summary>
        internal static string CRM_TestActivity_TestEnviromentConfiguration {
            get {
                return ResourceManager.GetString("CRM_TestActivity_TestEnviromentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_testpath.
        /// </summary>
        internal static string CRM_TestActivity_TestPath {
            get {
                return ResourceManager.GetString("CRM_TestActivity_TestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdb_testresult.
        /// </summary>
        internal static string CRM_TestActivity_TestResultforEachPath {
            get {
                return ResourceManager.GetString("CRM_TestActivity_TestResultforEachPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new_testtype.
        /// </summary>
        internal static string CRM_TestActivity_TestType {
            get {
                return ResourceManager.GetString("CRM_TestActivity_TestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to systemuser.
        /// </summary>
        internal static string CRM_User_EntitySchemaName {
            get {
                return ResourceManager.GetString("CRM_User_EntitySchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domainname.
        /// </summary>
        internal static string CRM_User_Name {
            get {
                return ResourceManager.GetString("CRM_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.CRMError.
        /// </summary>
        internal static string CRMError {
            get {
                return ResourceManager.GetString("CRMError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.DevelopTest.
        /// </summary>
        internal static string DevelopTest {
            get {
                return ResourceManager.GetString("DevelopTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.VSTS.Scheduling.Effort.
        /// </summary>
        internal static string Effort {
            get {
                return ResourceManager.GetString("Effort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlannedReleaseVersion.
        /// </summary>
        internal static string Global_PlannedReleaseVersion {
            get {
                return ResourceManager.GetString("Global_PlannedReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ID.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.InProgressTimeHours.
        /// </summary>
        internal static string InProgressTimeHours {
            get {
                return ResourceManager.GetString("InProgressTimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.InProgressTimeSpan.
        /// </summary>
        internal static string InProgressTimeSpan {
            get {
                return ResourceManager.GetString("InProgressTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.IsReopen.
        /// </summary>
        internal static string IsReopen {
            get {
                return ResourceManager.GetString("IsReopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IterationPath.
        /// </summary>
        internal static string Iteration {
            get {
                return ResourceManager.GetString("Iteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.LinkTypes.Hierarchy-Forward.
        /// </summary>
        internal static string LinkParent_Forward {
            get {
                return ResourceManager.GetString("LinkParent_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.LinkTypes.Hierarchy-Reverse.
        /// </summary>
        internal static string LinkParent_Reverse {
            get {
                return ResourceManager.GetString("LinkParent_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.LinkType.Tasks-Forward.
        /// </summary>
        internal static string LinkTask_Forward {
            get {
                return ResourceManager.GetString("LinkTask_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.LinkType.Tasks-Reverse.
        /// </summary>
        internal static string LinkTask_Reverse {
            get {
                return ResourceManager.GetString("LinkTask_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.NeginLite.BranchVersion.
        /// </summary>
        internal static string NeginLiteBranchVersion {
            get {
                return ResourceManager.GetString("NeginLiteBranchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.NeginLite.TrunkVersion.
        /// </summary>
        internal static string NeginLiteTrunkVersion {
            get {
                return ResourceManager.GetString("NeginLiteTrunkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.VSTS.Scheduling.OriginalEstimate.
        /// </summary>
        internal static string OriginalEstimate {
            get {
                return ResourceManager.GetString("OriginalEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.PRV.
        /// </summary>
        internal static string PlannedReleaseVersion {
            get {
                return ResourceManager.GetString("PlannedReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.ReferenceNumber.
        /// </summary>
        internal static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.ReferencePath.
        /// </summary>
        internal static string ReferencePath {
            get {
                return ResourceManager.GetString("ReferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.RelatedTestCases.
        /// </summary>
        internal static string RelatedTestCases {
            get {
                return ResourceManager.GetString("RelatedTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.VSTS.Scheduling.RemainingWork.
        /// </summary>
        internal static string RemainingWork {
            get {
                return ResourceManager.GetString("RemainingWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.ReopenCount.
        /// </summary>
        internal static string ReopenCount {
            get {
                return ResourceManager.GetString("ReopenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Rev.
        /// </summary>
        internal static string Rev {
            get {
                return ResourceManager.GetString("Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.RFCId.
        /// </summary>
        internal static string RFCId {
            get {
                return ResourceManager.GetString("RFCId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.RFCNumber.
        /// </summary>
        internal static string RFCNumber {
            get {
                return ResourceManager.GetString("RFCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.Scheduling.Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.VSTS.Common.Severity.
        /// </summary>
        internal static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.TestEnviromentConfiguration.
        /// </summary>
        internal static string TestEnviromentConfiguration {
            get {
                return ResourceManager.GetString("TestEnviromentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.TestPaths.
        /// </summary>
        internal static string TestPaths {
            get {
                return ResourceManager.GetString("TestPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.TestResult.
        /// </summary>
        internal static string TestResultforEachPath {
            get {
                return ResourceManager.GetString("TestResultforEachPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.TestType.
        /// </summary>
        internal static string TestType {
            get {
                return ResourceManager.GetString("TestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.VSTS.Common.Triage.
        /// </summary>
        internal static string Triage {
            get {
                return ResourceManager.GetString("Triage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.WorkItemType.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tosan.WebConsole.
        /// </summary>
        internal static string WebConsole {
            get {
                return ResourceManager.GetString("WebConsole", resourceCulture);
            }
        }
    }
}
