//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tosan.TeamFoundation.Plugins.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FieldValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tosan.TeamFoundation.Plugins.Resources.FieldValues", typeof(FieldValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرم افزاری.
        /// </summary>
        internal static string ChangeType_Applications {
            get {
                return ResourceManager.GetString("ChangeType_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر Model.
        /// </summary>
        internal static string ChangeType_Change_Model {
            get {
                return ResourceManager.GetString("ChangeType_Change_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Review.
        /// </summary>
        internal static string ChangeType_Code_Review {
            get {
                return ResourceManager.GetString("ChangeType_Code_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیکر بندی.
        /// </summary>
        internal static string ChangeType_Configuration {
            get {
                return ResourceManager.GetString("ChangeType_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سخت افزاری.
        /// </summary>
        internal static string ChangeType_Hardware {
            get {
                return ResourceManager.GetString("ChangeType_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر ساختی.
        /// </summary>
        internal static string ChangeType_Infrastructure {
            get {
                return ResourceManager.GetString("ChangeType_Infrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string Reason_Accepted {
            get {
                return ResourceManager.GetString("Reason_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional work found.
        /// </summary>
        internal static string Reason_AdditionalWorkFound {
            get {
                return ResourceManager.GetString("Reason_AdditionalWorkFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Reason_Approved {
            get {
                return ResourceManager.GetString("Reason_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Reason_Canceled {
            get {
                return ResourceManager.GetString("Reason_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed in Error.
        /// </summary>
        internal static string Reason_ClosedinError {
            get {
                return ResourceManager.GetString("Reason_ClosedinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete &amp; Requires Test.
        /// </summary>
        internal static string Reason_Complete_RequiresTest {
            get {
                return ResourceManager.GetString("Reason_Complete_RequiresTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Complete.
        /// </summary>
        internal static string Reason_DevComplete {
            get {
                return ResourceManager.GetString("Reason_DevComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Complete/Review.
        /// </summary>
        internal static string Reason_DevComplete_Review {
            get {
                return ResourceManager.GetString("Reason_DevComplete_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not Require Test.
        /// </summary>
        internal static string Reason_DoesNotRequireTest {
            get {
                return ResourceManager.GetString("Reason_DoesNotRequireTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string Reason_Duplicate {
            get {
                return ResourceManager.GetString("Reason_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string Reason_Fixed {
            get {
                return ResourceManager.GetString("Reason_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Complete.
        /// </summary>
        internal static string Reason_InvestigationComplete {
            get {
                return ResourceManager.GetString("Reason_InvestigationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Not Rejected.
        /// </summary>
        internal static string Reason_IsNotRejected {
            get {
                return ResourceManager.GetString("Reason_IsNotRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Reason_New {
            get {
                return ResourceManager.GetString("Reason_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        internal static string Reason_NewTask {
            get {
                return ResourceManager.GetString("Reason_NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not fixed.
        /// </summary>
        internal static string Reason_Notfixed {
            get {
                return ResourceManager.GetString("Reason_Notfixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivated.
        /// </summary>
        internal static string Reason_Reactivated {
            get {
                return ResourceManager.GetString("Reason_Reactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconsidering the Task.
        /// </summary>
        internal static string Reason_ReconsideringtheTask {
            get {
                return ResourceManager.GetString("Reason_ReconsideringtheTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Reason_Rejected {
            get {
                return ResourceManager.GetString("Reason_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected from test.
        /// </summary>
        internal static string Reason_Rejectedfromtest {
            get {
                return ResourceManager.GetString("Reason_Rejectedfromtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from the backlog.
        /// </summary>
        internal static string Reason_Removedfromthebacklog {
            get {
                return ResourceManager.GetString("Reason_Removedfromthebacklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review/Test Failed.
        /// </summary>
        internal static string Reason_Review_TestFailed {
            get {
                return ResourceManager.GetString("Reason_Review_TestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review/Test Passed.
        /// </summary>
        internal static string Reason_Review_TestPassed {
            get {
                return ResourceManager.GetString("Reason_Review_TestPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Failed.
        /// </summary>
        internal static string Reason_TestFailed {
            get {
                return ResourceManager.GetString("Reason_TestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Task Is Blocked.
        /// </summary>
        internal static string Reason_TheTaskIsBlocked {
            get {
                return ResourceManager.GetString("Reason_TheTaskIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TAsk Is Unblocked.
        /// </summary>
        internal static string Reason_TheTAskIsUnblocked {
            get {
                return ResourceManager.GetString("Reason_TheTAskIsUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string Reason_Verified {
            get {
                return ResourceManager.GetString("Reason_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Changelist.
        /// </summary>
        internal static string Reason_WithoutChangeList {
            get {
                return ResourceManager.GetString("Reason_WithoutChangeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work finished.
        /// </summary>
        internal static string Reason_WorkFinished {
            get {
                return ResourceManager.GetString("Reason_WorkFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work is Canceled.
        /// </summary>
        internal static string Reason_WorkisCanceled {
            get {
                return ResourceManager.GetString("Reason_WorkisCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work started.
        /// </summary>
        internal static string Reason_WorkStarted {
            get {
                return ResourceManager.GetString("Reason_WorkStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work stopped.
        /// </summary>
        internal static string Reason_WorkStopped {
            get {
                return ResourceManager.GetString("Reason_WorkStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocker.
        /// </summary>
        internal static string Severity_Blocker {
            get {
                return ResourceManager.GetString("Severity_Blocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string Severity_Critical {
            get {
                return ResourceManager.GetString("Severity_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string State_Active {
            get {
                return ResourceManager.GetString("State_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string State_Blocked {
            get {
                return ResourceManager.GetString("State_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string State_Closed {
            get {
                return ResourceManager.GetString("State_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string State_Done {
            get {
                return ResourceManager.GetString("State_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string State_InProgress {
            get {
                return ResourceManager.GetString("State_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed.
        /// </summary>
        internal static string State_Proposed {
            get {
                return ResourceManager.GetString("State_Proposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        internal static string State_Removed {
            get {
                return ResourceManager.GetString("State_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        internal static string State_Resolved {
            get {
                return ResourceManager.GetString("State_Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested.
        /// </summary>
        internal static string State_Tested {
            get {
                return ResourceManager.GetString("State_Tested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Do.
        /// </summary>
        internal static string State_ToDo {
            get {
                return ResourceManager.GetString("State_ToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconsidering the Task.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه ریزی شده نگهداری.
        /// </summary>
        internal static string Triage_DevPlanned {
            get {
                return ResourceManager.GetString("Triage_DevPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه ریزی نشده.
        /// </summary>
        internal static string Triage_NotPlanned {
            get {
                return ResourceManager.GetString("Triage_NotPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه ریزی شده.
        /// </summary>
        internal static string Triage_Planned {
            get {
                return ResourceManager.GetString("Triage_Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه ریزی شده تست.
        /// </summary>
        internal static string Triage_TestPlanned {
            get {
                return ResourceManager.GetString("Triage_TestPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Task.
        /// </summary>
        internal static string WI_AnalysisTask {
            get {
                return ResourceManager.GetString("WI_AnalysisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        internal static string WI_Bug {
            get {
                return ResourceManager.GetString("WI_Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Task.
        /// </summary>
        internal static string WI_DevTask {
            get {
                return ResourceManager.GetString("WI_DevTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        internal static string WI_Feature {
            get {
                return ResourceManager.GetString("WI_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelatedLink.
        /// </summary>
        internal static string WI_Link_Related {
            get {
                return ResourceManager.GetString("WI_Link_Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Backlog Item.
        /// </summary>
        internal static string WI_ProductBacklogItem {
            get {
                return ResourceManager.GetString("WI_ProductBacklogItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement.
        /// </summary>
        internal static string WI_Requirement {
            get {
                return ResourceManager.GetString("WI_Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string WI_Task {
            get {
                return ResourceManager.GetString("WI_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Task.
        /// </summary>
        internal static string WI_TestTask {
            get {
                return ResourceManager.GetString("WI_TestTask", resourceCulture);
            }
        }
    }
}
