//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TosanTFS.Web.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bn_Changeset
    {
        public bn_Changeset()
        {
            this.bn_WorkItems = new HashSet<bn_WorkItems>();
        }
    
        public Nullable<int> ChangeSetId { get; set; }
        public System.Guid LabelId { get; set; }
        public System.Guid id { get; set; }
    
        public virtual bn_Label bn_Label { get; set; }
        public virtual ICollection<bn_WorkItems> bn_WorkItems { get; set; }
    }
}
