//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TosanTFS.Web.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bn_Label
    {
        public bn_Label()
        {
            this.bn_Changeset = new HashSet<bn_Changeset>();
        }
    
        public string Label { get; set; }
        public string Dir { get; set; }
        public System.Guid id { get; set; }
    
        public virtual ICollection<bn_Changeset> bn_Changeset { get; set; }
    }
}
