//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TosanTFS.Web.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bn_WorkItems
    {
        public string Title { get; set; }
        public string State { get; set; }
        public string FixedVersion { get; set; }
        public string Severity { get; set; }
        public string Customer { get; set; }
        public string RFCNumber { get; set; }
        public string Area { get; set; }
        public System.Guid ChangeSetId { get; set; }
        public System.Guid id { get; set; }
    
        public virtual bn_Changeset bn_Changeset { get; set; }
    }
}
