//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TosanTFS.Web.Service.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TFSExtensionCon : DbContext
    {
        public TFSExtensionCon()
            : base("name=TFSExtensionCon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bn_Changeset> bn_Changeset { get; set; }
        public DbSet<bn_Label> bn_Label { get; set; }
        public DbSet<bn_WorkItems> bn_WorkItems { get; set; }
    }
}
